- name: "Lawn and Landscape"
  icon: "shopping-cart"
  description: "Our commercial fleet handles large or small contracts with ease and we're able to keep your property beautiful with your landscaping needs."
- name: "Snow Removal"
  icon: "laptop"
  description: "We provide peace-of-mind for area churches, schools, businesses, government offices, and local residents when the weather is at its worst."
- name: "Renovations, Remodelling, General Contracting"
  icon: "home"
  description: "We handle everything from historic renovations and commercial remodelling to custom-taylored development."
